from enum import Enum


class CommunicationMessageTypes(str, Enum):
    LOGIN = 'LOGIN'
    PEERS_LIST = 'PEERS_LIST'
    INFO = 'INFO'
    HASHGRAPH = 'HASHGRAPH'
    BLOCK = 'BLOCK'
    ACK = 'ACK'
    NACK = 'NACK'
    POSITIONS_DEGREES = 'POSITIONS_DEGREES'
    TRANSACTION_GET = 'TRANSACTION_GET'
    POSITIONS_DEGREES_GET = 'POSITIONS_DEGREES_GET'
    POSITIONS_DEGREES_GET_RESPONSE = 'POSITIONS_DEGREES_GET_RESPONSE'
    TRANSACTION_GET_RESPONSE = 'TRANSACTION_GET_RESPONSE'
